const $ = (s, e=document) => e.querySelector(s);
const blocks = $('#blocks'), blockTpl = $('#block-template'), repTpl = $('#rep-template');
const key = 'lane-lines-sets-v1', logKey = 'lane-lines-workout-log-v1', syncKey = 'lane-lines-github-sync-v1', logSyncKey = 'lane-lines-workout-log-github-sync-v1';
const sampleCleanupKey = 'lane-lines-sample-cleanup-v1';
const requestedWorkoutSeedKey = 'lane-lines-requested-workouts-v1';
const requestedLibrary=[
  {title:'Freestyle Pace Ladder',focus:'Aerobic pacing and control',tags:'freestyle, aerobic, pacing',pool:'25',savedAt:1786298400000,blocks:[{name:'Warm-up',note:'Build gradually and establish a calm breathing pattern.',reps:[{count:1,distance:400,stroke:'Choice',interval:'',detail:'swim / kick / drill'}]},{name:'Pace ladder',note:'Hold a steady stroke count as the distance changes.',reps:[{count:1,distance:100,stroke:'Freestyle',interval:'1:35',detail:'smooth'},{count:1,distance:200,stroke:'Freestyle',interval:'3:05',detail:'steady'},{count:1,distance:300,stroke:'Freestyle',interval:'4:35',detail:'strong'},{count:1,distance:200,stroke:'Freestyle',interval:'3:00',detail:'steady'},{count:1,distance:100,stroke:'Freestyle',interval:'1:30',detail:'build'}]},{name:'Warm-down',note:'Easy choice.',reps:[{count:1,distance:200,stroke:'Choice',interval:'',detail:''}]}]},
  {title:'IM Transitions',focus:'IM skills and clean turns',tags:'IM, technique, turns',pool:'25',savedAt:1786298400001,blocks:[{name:'Warm-up',note:'Prepare each stroke with good body line.',reps:[{count:4,distance:75,stroke:'IM',interval:'1:25',detail:'25 drill / 50 swim'}]},{name:'IM circuit',note:'Make every transition deliberate.',reps:[{count:4,distance:100,stroke:'IM',interval:'1:45',detail:'descend 1–4'}],children:[{name:'Transition skills',note:'Reset and focus on the wall.',reps:[{count:4,distance:50,stroke:'Choice',interval:'1:05',detail:'25 fast into turn + 25 easy'}]}]},{name:'Warm-down',note:'Easy choice.',reps:[{count:1,distance:300,stroke:'Choice',interval:'',detail:''}]}]},
  {title:'50 Race Pace',focus:'Speed, walls, and recovery',tags:'sprint, race pace, speed',pool:'25',savedAt:1786298400002,blocks:[{name:'Warm-up',note:'Build speed through the walls.',reps:[{count:1,distance:500,stroke:'Choice',interval:'',detail:'swim / drill / kick'}]},{name:'Race pace',note:'Quality first. Take the easy repeats seriously.',reps:[{count:8,distance:50,stroke:'Freestyle',interval:'1:15',detail:'odds race pace, evens easy'}]},{name:'Breakout work',note:'Fast into a clean breakout.',repeat:2,reps:[{count:4,distance:25,stroke:'Choice',interval:':40',detail:'15 m fast, easy in'}]},{name:'Warm-down',note:'Easy choice.',reps:[{count:1,distance:300,stroke:'Choice',interval:'',detail:''}]}]}
];
const requestedLogs=[
  {title:'Freestyle Pace Ladder',date:'2026-08-08',total:1500,unit:'yd',notes:'Strong pacing through the middle 300; held stroke count well.',set:requestedLibrary[0]},
  {title:'IM Transitions',date:'2026-08-06',total:1200,unit:'yd',notes:'Better breaststroke-to-free transitions by the final round.',set:requestedLibrary[1]},
  {title:'50 Race Pace',date:'2026-08-04',total:1400,unit:'yd',notes:'High-quality 50s with focused turns and underwater breakouts.',set:requestedLibrary[2]}
];
const starter = [
  {name:'Warm-up',note:'Build into the practice. Focus on long lines and steady breathing.',reps:[{count:1,distance:400,stroke:'Choice',interval:'',detail:'swim + kick + drill'}]},
  {name:'Pre-set',note:'Hold form as the send-off tightens.',reps:[{count:4,distance:100,stroke:'Freestyle',interval:'1:35',detail:'descend 1–4'},{count:4,distance:50,stroke:'Kick',interval:'1:05',detail:'strong underwater work'}]},
  {name:'Main set',note:'Threshold effort — aim to hold your best sustainable pace.',reps:[{count:6,distance:200,stroke:'Freestyle',interval:'2:40',detail:'negative split'},{count:4,distance:50,stroke:'Choice',interval:'1:00',detail:'easy'}]},
  {name:'Warm-down',note:'Easy choice.',reps:[{count:1,distance:200,stroke:'Choice',interval:'',detail:''}]}
];
const starterLibrary=[
  {title:'Sprint & Turns',focus:'Speed, turns, and race details',tags:'sprint, race pace, turns',pool:'25',blocks:[{name:'Warm-up',note:'Build into speed with excellent walls.',reps:[{count:1,distance:500,stroke:'Choice',interval:'',detail:'swim / kick / drill'},{count:4,distance:50,stroke:'Choice',interval:'1:00',detail:'build to 90%'}]},{name:'Speed set',note:'Quality over quantity. Full attention at every wall.',reps:[{count:8,distance:25,stroke:'Choice',interval:':40',detail:'from a push, fast breakout'},{count:6,distance:50,stroke:'Freestyle',interval:'1:30',detail:'race pace, perfect turns'}]},{name:'Warm-down',note:'Easy choice.',reps:[{count:1,distance:300,stroke:'Choice',interval:'',detail:''}]}]},
  {title:'IM Precision',focus:'Stroke technique and IM transitions',tags:'IM, stroke, technique',pool:'25',blocks:[{name:'Warm-up',note:'Prioritize body line and rhythm.',reps:[{count:4,distance:100,stroke:'IM',interval:'1:50',detail:'25 drill / 75 swim'}]},{name:'IM set',note:'Stay disciplined through every transition.',reps:[{count:4,distance:100,stroke:'IM',interval:'1:40',detail:'descend 1–4'},{count:8,distance:50,stroke:'Choice',interval:'1:00',detail:'odds stroke, evens free'}]},{name:'Warm-down',note:'Easy choice.',reps:[{count:1,distance:300,stroke:'Choice',interval:'',detail:''}]}]},
  {title:'Distance Ladder',focus:'Aerobic endurance and pacing',tags:'distance, aerobic, freestyle',pool:'25',blocks:[{name:'Warm-up',note:'Find a steady aerobic rhythm.',reps:[{count:1,distance:600,stroke:'Choice',interval:'',detail:'every 4th length kick'}]},{name:'Ladder',note:'Hold your pace; descend the effort by round.',reps:[{count:1,distance:100,stroke:'Freestyle',interval:'1:30',detail:'round 1 smooth'},{count:1,distance:200,stroke:'Freestyle',interval:'2:55',detail:'round 2 steady'},{count:1,distance:300,stroke:'Freestyle',interval:'4:20',detail:'round 3 strong'},{count:1,distance:400,stroke:'Freestyle',interval:'5:40',detail:'round 4 best sustainable pace'},{count:1,distance:300,stroke:'Freestyle',interval:'4:15',detail:'round 5 strong'},{count:1,distance:200,stroke:'Freestyle',interval:'2:50',detail:'round 6 steady'},{count:1,distance:100,stroke:'Freestyle',interval:'1:25',detail:'round 7 fast finish'}]},{name:'Warm-down',note:'Easy choice.',reps:[{count:1,distance:300,stroke:'Choice',interval:'',detail:''}]}]},
  {title:'Meet Prep',focus:'Race rehearsal without fatigue',tags:'meet prep, race pace, recovery',pool:'25',blocks:[{name:'Warm-up',note:'Stay relaxed and purposeful.',reps:[{count:1,distance:400,stroke:'Choice',interval:'',detail:'swim + drill'}]},{name:'Race rehearsal',note:'Choose your primary event stroke. Plenty of recovery.',reps:[{count:4,distance:50,stroke:'Choice',interval:'1:20',detail:'25 build + 25 easy'},{count:2,distance:100,stroke:'Choice',interval:'3:00',detail:'race pace from a push'},{count:4,distance:25,stroke:'Choice',interval:':45',detail:'fast breakout to 15m'}]},{name:'Warm-down',note:'Easy choice.',reps:[{count:1,distance:400,stroke:'Choice',interval:'',detail:''}]}]}
];
function val(el, cls){ return $('.'+cls,el).value }
function addRep(reps,data={count:4,distance:100,stroke:'Freestyle',interval:'1:30',detail:''}){const node=repTpl.content.firstElementChild.cloneNode(true);Object.entries(data).forEach(([k,v])=>{$('.'+k,node).value=v});$('.delete-rep',node).onclick=()=>{node.remove();updateTotals()};node.querySelectorAll('input,select').forEach(e=>e.addEventListener('input',updateTotals));reps.append(node)}
function readReps(reps){return [...reps.querySelectorAll(':scope > .rep')].map(r=>({count:+val(r,'count')||0,distance:+val(r,'distance')||0,stroke:val(r,'stroke'),interval:val(r,'interval'),detail:val(r,'detail')}))}
function addBlock(container,data={name:'New block',note:'',repeat:1,reps:[{count:4,distance:100,stroke:'Freestyle',interval:'1:30',detail:''}],children:[]}){
  const node=blockTpl.content.firstElementChild.cloneNode(true), childBlocks=$('.child-blocks',node);
  $('.block-name',node).value=data.name; $('.block-note',node).value=data.note; $('.block-repeat',node).value=data.repeat||1;
  (data.reps||[]).forEach(r=>addRep($('.block-reps',node),r));
  (data.children||data.subblocks||[]).forEach(child=>addBlock(childBlocks,child));
  $('.add-rep',node).onclick=()=>{addRep($('.block-reps',node));updateTotals()};
  $('.add-child-block',node).onclick=()=>{addBlock(childBlocks);updateTotals()};
  $('.delete-block',node).onclick=()=>{if(container===blocks&&blocks.children.length<=1)toast('Keep at least one top-level block in your set.');else{node.remove();updateTotals()}};
  $('.duplicate',node).onclick=()=>{addBlock(container,readBlock(node));updateTotals()};
  node.querySelectorAll('input,textarea,select').forEach(e=>e.addEventListener('input',updateTotals));
  container.append(node); updateTotals(); return node;
}
function readBlock(node){return {name:val(node,'block-name'),note:val(node,'block-note'),repeat:+val(node,'block-repeat')||1,reps:readReps($('.block-reps',node)),children:[...$('.child-blocks',node).children].map(readBlock)}}
function currentSet(){return {title:$('#set-title').value.trim()||'Untitled set',focus:$('#set-focus').value,tags:$('#set-tags').value,pool:$('#pool-length').value,blocks:[...blocks.children].map(readBlock)}}
function intervalSeconds(s){const m=s.trim().match(/^(?:(\d+):)?(\d{1,2})$/);return m?(+(m[1]||0)*60 + +m[2]):0}
function setTotals(set){let distance=0,seconds=0;const addBlockTotals=(block,parentRepeat=1)=>{const repeat=parentRepeat*(+block.repeat||1);(block.reps||[]).forEach(r=>{distance+=repeat*(+r.count||0)*(+r.distance||0);seconds+=repeat*(+r.count||0)*intervalSeconds(r.interval||'')});(block.children||block.subblocks||[]).forEach(child=>addBlockTotals(child,repeat))};(set.blocks||[]).forEach(block=>addBlockTotals(block));return{distance,seconds}}
function updateTotals(){const totals=setTotals(currentSet());$('#total-yards').textContent=`${totals.distance.toLocaleString()} ${$('#pool-length').value==='25'?'yd':'m'}`;$('#total-time').textContent=totals.seconds?`Estimated interval time: ${Math.floor(totals.seconds/60)} min ${totals.seconds%60} sec`:'Add intervals to estimate time'}
function allSaved(){try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return []}}
function allLogs(){try{return JSON.parse(localStorage.getItem(logKey)||'[]')}catch{return []}}
function syncSettings(){try{return JSON.parse(localStorage.getItem(syncKey)||'{}')}catch{return {}}}
function saveSyncSettings(settings){localStorage.setItem(syncKey,JSON.stringify(settings))}
function logSyncSettings(){try{const own=JSON.parse(localStorage.getItem(logSyncKey)||'{}'),library=syncSettings();return{repository:own.repository||library.repository||'',branch:own.branch||library.branch||'main',file:own.file||'swim-workout-log.json',token:own.token||library.token||'',lastSyncedSha:own.lastSyncedSha||''}}catch{return {file:'swim-workout-log.json',branch:'main'}}}
function saveLogSyncSettings(settings){localStorage.setItem(logSyncKey,JSON.stringify(settings))}
function updateSyncControls(){const connected=Boolean(syncSettings().repository);$('#library-sync-settings').textContent=connected?'GitHub settings':'Connect GitHub';$('#library-pull').disabled=!connected;$('#library-push').disabled=!connected;$('#library-pull').title=connected?'Replace this device’s library with the shared GitHub library':'Connect GitHub first';$('#library-push').title=connected?'Save this device’s library to GitHub':'Connect GitHub first'}
function updateLogSyncControls(){const connected=Boolean(logSyncSettings().repository&&logSyncSettings().token);$('#log-sync-settings').textContent=connected?'GitHub settings':'Connect GitHub';$('#log-pull').disabled=!connected;$('#log-push').disabled=!connected;$('#log-pull').title=connected?'Replace this device’s workout log with the shared GitHub log':'Connect GitHub first';$('#log-push').title=connected?'Save this device’s workout log to GitHub':'Connect GitHub first'}
function openSyncSettings(){const settings=syncSettings();$('#github-repository').value=settings.repository||'stebb1976/lane-lines-swim-set-builder';$('#github-branch').value=settings.branch||'main';$('#github-file').value=settings.file||'swim-set-library.json';$('#github-token').value=settings.token||'';$('#sync-dialog').showModal()}
function openLogSyncSettings(){const settings=logSyncSettings();$('#log-github-repository').value=settings.repository||'stebb1976/lane-lines-swim-set-builder';$('#log-github-branch').value=settings.branch||'main';$('#log-github-file').value=settings.file||'swim-workout-log.json';$('#log-github-token').value=settings.token||'';$('#log-sync-dialog').showModal()}
function githubApi(settings){return `https://api.github.com/repos/${settings.repository}/contents/${settings.file.split('/').map(encodeURIComponent).join('/')}`}
function githubHeaders(settings){return {'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2026-03-10',...(settings.token?{'Authorization':`Bearer ${settings.token}`}:{})}}
function githubFileRequest(settings){return fetch(`${githubApi(settings)}?ref=${encodeURIComponent(settings.branch||'main')}&_=${Date.now()}`,{headers:githubHeaders(settings),cache:'no-store'})}
function decodeBase64(value){return new TextDecoder().decode(Uint8Array.from(atob(value.replace(/\n/g,'')),char=>char.charCodeAt(0)))}
function encodeBase64(value){return btoa(String.fromCharCode(...new TextEncoder().encode(value)))}
function mergeLibraries(local,remote){const combined=new Map;[...remote,...local].forEach(set=>{const existing=combined.get(set.title);if(!existing||(+set.savedAt||0)>=(+existing.savedAt||0))combined.set(set.title,set)});return [...combined.values()].sort((a,b)=>(+b.savedAt||0)-(+a.savedAt||0))}
let pendingConflict;
function rememberSyncedSha(settings,sha){saveSyncSettings({...settings,lastSyncedSha:sha})}
async function pullLibrary(){const settings=syncSettings();if(!settings.repository){openSyncSettings();return}try{const response=await githubFileRequest(settings);if(!response.ok)throw new Error(response.status===404?'The JSON file was not found yet. Save your library first.':`GitHub returned ${response.status}.`);const file=await response.json(),payload=JSON.parse(decodeBase64(file.content)),remote=Array.isArray(payload)?payload:payload.sets;if(!Array.isArray(remote))throw new Error('That file does not contain a set library.');localStorage.setItem(key,JSON.stringify(remote));rememberSyncedSha(settings,file.sha);renderLibrary();toast('Library loaded from GitHub.')}catch(error){toast(error.message||'Could not load the GitHub library.')}}
async function showLatestConflict(settings){const response=await githubFileRequest(settings);if(!response.ok)return false;pendingConflict={settings,file:await response.json()};$('#sync-conflict-dialog').showModal();return true}
async function pushLibrary(force=false,retry=0){const settings=syncSettings();if(!settings.repository||!settings.token){openSyncSettings();return}const content=JSON.stringify({version:1,updatedAt:new Date().toISOString(),sets:allSaved()},null,2);try{const endpoint=githubApi(settings),check=await githubFileRequest(settings);if(!check.ok&&check.status!==404)throw new Error(`GitHub returned ${check.status}.`);const existing=check.ok?await check.json():null;if(existing&&!force&&settings.lastSyncedSha!==existing.sha){pendingConflict={settings,file:existing};$('#sync-conflict-dialog').showModal();return}const response=await fetch(endpoint,{method:'PUT',headers:{...githubHeaders(settings),'Content-Type':'application/json'},body:JSON.stringify({message:'Sync swim set library',content:encodeBase64(content),branch:settings.branch||'main',...(existing?{sha:existing.sha}:{})})});if(!response.ok){if(response.status===409&&force&&retry===0)return pushLibrary(true,1);if(response.status===409&&!force&&await showLatestConflict(settings))return;const detail=await response.json().catch(()=>null);throw new Error(detail?.message||'GitHub changed the library again while saving. Please try once more.')}const result=await response.json();rememberSyncedSha(settings,result.content?.sha||existing?.sha||'');toast('Library saved to GitHub.')}catch(error){toast(error.message||'Could not save the GitHub library.')}}
async function mergeThenPush(){if(!pendingConflict)return;const {settings,file}=pendingConflict;try{const payload=JSON.parse(decodeBase64(file.content)),remote=Array.isArray(payload)?payload:payload.sets;if(!Array.isArray(remote))throw new Error('That file does not contain a set library.');localStorage.setItem(key,JSON.stringify(mergeLibraries(allSaved(),remote)));rememberSyncedSha(settings,file.sha);renderLibrary();$('#sync-conflict-dialog').close();pendingConflict=undefined;await pushLibrary(true)}catch(error){toast(error.message||'Could not merge the GitHub library.')}}
let pendingLogConflict;
function rememberLogSyncedSha(settings,sha){saveLogSyncSettings({...settings,lastSyncedSha:sha})}
function mergeLogs(local,remote){const combined=new Map;[...remote,...local].forEach(log=>combined.set(`${log.title}|${log.date}`,log));return [...combined.values()].sort((a,b)=>String(b.date).localeCompare(String(a.date)))}
async function pullLog(){const settings=logSyncSettings();if(!settings.repository||!settings.token){openLogSyncSettings();return}try{const response=await githubFileRequest(settings);if(!response.ok)throw new Error(response.status===404?'The log JSON file was not found yet. Save your log first.':`GitHub returned ${response.status}.`);const file=await response.json(),payload=JSON.parse(decodeBase64(file.content)),remote=Array.isArray(payload)?payload:payload.logs;if(!Array.isArray(remote))throw new Error('That file does not contain a workout log.');localStorage.setItem(logKey,JSON.stringify(remote));rememberLogSyncedSha(settings,file.sha);renderLog();toast('Workout log loaded from GitHub.')}catch(error){toast(error.message||'Could not load the GitHub workout log.')}}
async function showLatestLogConflict(settings){const response=await githubFileRequest(settings);if(!response.ok)return false;pendingLogConflict={settings,file:await response.json()};$('#log-sync-conflict-dialog').showModal();return true}
async function pushLog(force=false,retry=0){const settings=logSyncSettings();if(!settings.repository||!settings.token){openLogSyncSettings();return}const content=JSON.stringify({version:1,updatedAt:new Date().toISOString(),logs:allLogs()},null,2);try{const endpoint=githubApi(settings),check=await githubFileRequest(settings);if(!check.ok&&check.status!==404)throw new Error(`GitHub returned ${check.status}.`);const existing=check.ok?await check.json():null;if(existing&&!force&&settings.lastSyncedSha!==existing.sha){pendingLogConflict={settings,file:existing};$('#log-sync-conflict-dialog').showModal();return}const response=await fetch(endpoint,{method:'PUT',headers:{...githubHeaders(settings),'Content-Type':'application/json'},body:JSON.stringify({message:'Sync swim workout log',content:encodeBase64(content),branch:settings.branch||'main',...(existing?{sha:existing.sha}:{})})});if(!response.ok){if(response.status===409&&force&&retry===0)return pushLog(true,1);if(response.status===409&&!force&&await showLatestLogConflict(settings))return;const detail=await response.json().catch(()=>null);throw new Error(detail?.message||'GitHub changed the workout log again while saving. Please try once more.')}const result=await response.json();rememberLogSyncedSha(settings,result.content?.sha||existing?.sha||'');toast('Workout log saved to GitHub.')}catch(error){toast(error.message||'Could not save the GitHub workout log.')}}
async function mergeLogThenPush(){if(!pendingLogConflict)return;const {settings,file}=pendingLogConflict;try{const payload=JSON.parse(decodeBase64(file.content)),remote=Array.isArray(payload)?payload:payload.logs;if(!Array.isArray(remote))throw new Error('That file does not contain a workout log.');localStorage.setItem(logKey,JSON.stringify(mergeLogs(allLogs(),remote)));rememberLogSyncedSha(settings,file.sha);renderLog();$('#log-sync-conflict-dialog').close();pendingLogConflict=undefined;await pushLog(true)}catch(error){toast(error.message||'Could not merge the GitHub workout log.')}}
function removeLegacySamples(){if(localStorage.getItem(sampleCleanupKey))return;const titles=new Set(['Sprint & Turns','IM Precision','Distance Ladder','Meet Prep']);localStorage.setItem(key,JSON.stringify(allSaved().filter(set=>!titles.has(set.title))));localStorage.setItem(logKey,JSON.stringify(allLogs().filter(log=>!titles.has(log.title))));localStorage.setItem(sampleCleanupKey,'true')}
function seedRequestedWorkouts(){if(localStorage.getItem(requestedWorkoutSeedKey))return;const saved=allSaved(),savedTitles=new Set(saved.map(set=>set.title)),logs=allLogs(),loggedTitles=new Set(logs.map(log=>`${log.title}|${log.date}`));localStorage.setItem(key,JSON.stringify([...requestedLibrary.filter(set=>!savedTitles.has(set.title)),...saved]));localStorage.setItem(logKey,JSON.stringify([...requestedLogs.filter(log=>!loggedTitles.has(`${log.title}|${log.date}`)),...logs]));localStorage.setItem(requestedWorkoutSeedKey,'true')}
function tagList(tags){return String(tags||'').split(',').map(t=>t.trim()).filter(Boolean)}
function duplicateTitle(title,saved){let number=1,candidate=`${title} Copy`;const names=new Set(saved.map(set=>set.title));while(names.has(candidate)){number++;candidate=`${title} Copy ${number}`}return candidate}
let pendingDeletion;
function requestDelete(message,action){pendingDeletion=action;$('#delete-message').textContent=message;$('#delete-confirm-dialog').showModal()}
function renderLibrary(){const saved=allSaved(),query=$('#library-search').value.trim().toLowerCase(),visible=saved.filter(s=>[s.title,s.focus,s.tags].join(' ').toLowerCase().includes(query)),area=$('#saved-sets');$('#library-count').textContent=saved.length?`${visible.length} of ${saved.length} saved set${saved.length===1?'':'s'}`:'';area.innerHTML=visible.length?'':`<p class="empty">${saved.length?'No sets match this search.':'No saved sets yet.'}</p>`;visible.forEach(s=>{const el=document.createElement('div');el.className='saved-set';const tags=tagList(s.tags).map(t=>`<span class="tag">${escapeHtml(t)}</span>`).join('');el.innerHTML=`<button class="load"><strong>${escapeHtml(s.title)}</strong><small>${s.blocks.length} blocks · ${escapeHtml(s.focus||'No focus')}</small>${tags?`<span class="set-tags">${tags}</span>`:''}</button><div class="set-actions"><button class="duplicate-set" title="Duplicate saved set">⧉</button><button class="trash" title="Delete saved set">×</button></div>`;$('.load',el).onclick=()=>{loadSet(s);closeLibrary()};$('.duplicate-set',el).onclick=()=>{const next=allSaved(),copy=JSON.parse(JSON.stringify(s));copy.title=duplicateTitle(s.title,next);copy.savedAt=Date.now();next.unshift(copy);localStorage.setItem(key,JSON.stringify(next));renderLibrary();toast(`Created ${copy.title}.`)};$('.trash',el).onclick=()=>requestDelete(`Delete “${s.title}” from your set library?`,()=>{const next=allSaved().filter(x=>x.title!==s.title);localStorage.setItem(key,JSON.stringify(next));renderLibrary();toast('Saved set deleted.')});area.append(el)})}
function renderLog(){const logs=allLogs(),area=$('#log-entries');$('#log-count').textContent=logs.length?`${logs.length} logged`:'';area.innerHTML=logs.length?'':'<p class="empty">No workouts logged yet.</p>';logs.forEach((log,i)=>{const el=document.createElement('article');el.className='log-entry';el.innerHTML=`<button class="load-log" title="Open this workout"><strong>${escapeHtml(log.title)}</strong><small>${escapeHtml(log.date)} · ${log.total.toLocaleString()} ${log.unit}</small>${log.notes?`<p class="log-note">${escapeHtml(log.notes)}</p>`:''}</button><button class="delete-log" title="Delete log entry">×</button>`;$('.load-log',el).onclick=()=>{if(log.set){loadSet(log.set);toast('Workout loaded from your log.')}else toast('This older log entry has no saved workout snapshot.')};$('.delete-log',el).onclick=()=>requestDelete(`Delete the ${log.date} workout log entry for “${log.title}”?`,()=>{const next=allLogs();next.splice(i,1);localStorage.setItem(logKey,JSON.stringify(next));renderLog();toast('Log entry deleted.')});area.append(el)})}
function addUnits(target,distance,unit){target[unit]=(target[unit]||0)+distance}
function unitText(units){return Object.entries(units).map(([unit,value])=>`${value.toLocaleString()} ${unit}`).join(' · ')||'0'}
function periodRows(logs,period){const buckets=new Map;logs.forEach(log=>{const date=new Date(`${log.date}T12:00:00`);if(Number.isNaN(date))return;let key,label;if(period==='week'){const monday=new Date(date);monday.setDate(date.getDate()-((date.getDay()+6)%7));key=monday.toISOString().slice(0,10);label=`Week of ${monday.toLocaleDateString(undefined,{month:'short',day:'numeric'})}`}else{key=log.date.slice(0,7);label=date.toLocaleDateString(undefined,{month:'short',year:'numeric'})}if(!buckets.has(key))buckets.set(key,{key,label,count:0,units:{}});const row=buckets.get(key);row.count++;addUnits(row.units,+log.total||0,log.unit||'yd')});return [...buckets.values()].sort((a,b)=>b.key.localeCompare(a.key))}
function strokeRows(logs){const buckets=new Map;logs.forEach(log=>log.set?.blocks?.forEach(block=>block.reps.forEach(rep=>{const stroke=rep.stroke||'Choice';if(!buckets.has(stroke))buckets.set(stroke,{label:stroke,units:{}});addUnits(buckets.get(stroke).units,(+rep.count||0)*(+rep.distance||0),log.unit||'yd')})));return [...buckets.values()].sort((a,b)=>Object.values(b.units).reduce((x,y)=>x+y,0)-Object.values(a.units).reduce((x,y)=>x+y,0))}
function strokeRows(logs){const buckets=new Map;const addBlockStrokes=(block,unit,parentRepeat=1)=>{const repeat=parentRepeat*(+block.repeat||1);(block.reps||[]).forEach(rep=>{const stroke=rep.stroke||'Choice';if(!buckets.has(stroke))buckets.set(stroke,{label:stroke,units:{}});addUnits(buckets.get(stroke).units,repeat*(+rep.count||0)*(+rep.distance||0),unit)});(block.children||block.subblocks||[]).forEach(child=>addBlockStrokes(child,unit,repeat))};logs.forEach(log=>(log.set?.blocks||[]).forEach(block=>addBlockStrokes(block,log.unit||'yd')));return [...buckets.values()].sort((a,b)=>Object.values(b.units).reduce((x,y)=>x+y,0)-Object.values(a.units).reduce((x,y)=>x+y,0))}
function statRows(rows,showCount=false){if(!rows.length)return '<p class="stats-empty">Log a workout to start seeing trends.</p>';const max=Math.max(...rows.map(row=>Object.values(row.units).reduce((a,b)=>a+b,0)),1);return rows.map(row=>{const value=Object.values(row.units).reduce((a,b)=>a+b,0);return `<div class="stat-row"><span class="stat-label">${escapeHtml(row.label)}</span><span class="stat-bar"><span style="width:${Math.max(3,value/max*100)}%"></span></span><span class="stat-value">${unitText(row.units)}${showCount?`<br><em>${row.count} practice${row.count===1?'':'s'}</em>`:''}</span></div>`}).join('')}
function renderStats(){const logs=allLogs(),weekly=periodRows(logs,'week'),monthly=periodRows(logs,'month'),strokes=strokeRows(logs);$('#stats-sheet').innerHTML=`<p class="deck-kicker">LANE LINES · TRAINING ANALYTICS</p><h1>Workout statistics</h1><p class="stats-subtitle">${logs.length} logged practice${logs.length===1?'':'s'} · totals are based on completed workouts in your log.</p><div class="stats-grid"><section class="stats-panel"><h2>By week</h2>${statRows(weekly,true)}</section><section class="stats-panel"><h2>By month</h2>${statRows(monthly,true)}</section><section class="stats-panel"><h2>Distance by stroke</h2>${statRows(strokes)}</section></div>`}
function openStats(){renderStats();document.body.classList.add('show-stats');$('#stats-view').setAttribute('aria-hidden','false');window.scrollTo(0,0)}
function closeStats(){document.body.classList.remove('show-stats');$('#stats-view').setAttribute('aria-hidden','true')}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[x]))}
function loadSet(s){$('#set-title').value=s.title;$('#display-title').textContent=s.title;$('#set-focus').value=s.focus||'';$('#set-tags').value=s.tags||'';$('#pool-length').value=s.pool||'25';blocks.innerHTML='';(s.blocks||[]).forEach(block=>addBlock(blocks,block));updateTotals();window.scrollTo({top:0,behavior:'smooth'});toast('Set loaded.')}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('visible');setTimeout(()=>t.classList.remove('visible'),2200)}
$('#add-block').onclick=()=>addBlock(blocks);$('#add-block-bottom').onclick=()=>addBlock(blocks);$('#new-set').onclick=()=>loadSet({title:'Untitled set',focus:'',pool:'25',blocks:[]});
function renderDeck(){const set=currentSet(),totals=setTotals(set),unit=set.pool==='25'?'yd':'m',time=totals.seconds?`${Math.floor(totals.seconds/60)} min ${totals.seconds%60} sec`:'—';$('#deck-sheet').innerHTML=`<p class="deck-kicker">HIGH SCHOOL SWIM · DECK SHEET</p><h1 class="deck-title">${escapeHtml(set.title)}</h1><div class="deck-meta"><span><strong>Focus</strong><br>${escapeHtml(set.focus||'—')}</span><span><strong>Pool</strong><br>${set.pool} ${unit} pool</span><span><strong>Total</strong><br>${totals.distance.toLocaleString()} ${unit}</span><span><strong>Interval time</strong><br>${time}</span></div>${set.blocks.map(block=>`<section class="deck-block"><h2>${escapeHtml(block.name)}</h2>${block.note?`<p class="deck-note">${escapeHtml(block.note)}</p>`:''}<table class="deck-table"><thead><tr><th>SET</th><th>STROKE</th><th>INTERVAL</th><th>DETAIL</th></tr></thead><tbody>${block.reps.map(r=>`<tr><td class="deck-setline">${r.count} × ${r.distance} ${unit}</td><td>${escapeHtml(r.stroke)}</td><td>${escapeHtml(r.interval||'—')}</td><td class="deck-detail">${escapeHtml(r.detail||'—')}</td></tr>`).join('')}</tbody></table></section>`).join('')}<footer class="deck-footer"><span>Lane Lines · ${new Date().toLocaleDateString()}</span><span>Good work. Swim with purpose.</span></footer>`}
function deckTable(reps,unit){return `<table class="deck-table"><thead><tr><th>SET</th><th>STROKE</th><th>INTERVAL</th><th>DETAIL</th></tr></thead><tbody>${reps.map(r=>`<tr><td class="deck-setline">${r.count} × ${r.distance} ${unit}</td><td>${escapeHtml(r.stroke)}</td><td>${escapeHtml(r.interval||'—')}</td><td class="deck-detail">${escapeHtml(r.detail||'—')}</td></tr>`).join('')}</tbody></table>`}
function deckBlock(block,unit,level=0){const heading=level===0?'h2':'h3',children=(block.children||block.subblocks||[]).map(child=>deckBlock(child,unit,level+1)).join('');return `<section class="deck-block${level?' deck-child-block':''}"><${heading}>${escapeHtml(block.name)}${(+block.repeat||1)>1?` <small>× ${block.repeat} rounds</small>`:''}</${heading}>${block.note?`<p class="deck-note">${escapeHtml(block.note)}</p>`:''}${(block.reps||[]).length?deckTable(block.reps,unit):''}${children}</section>`}
function renderDeck(){const set=currentSet(),totals=setTotals(set),unit=set.pool==='25'?'yd':'m',time=totals.seconds?`${Math.floor(totals.seconds/60)} min ${totals.seconds%60} sec`:'—',body=set.blocks.map(block=>deckBlock(block,unit)).join('');$('#deck-sheet').innerHTML=`<p class="deck-kicker">HIGH SCHOOL SWIM · DECK SHEET</p><h1 class="deck-title">${escapeHtml(set.title)}</h1><div class="deck-meta"><span><strong>Focus</strong><br>${escapeHtml(set.focus||'—')}</span><span><strong>Pool</strong><br>${set.pool} ${unit} pool</span><span><strong>Total</strong><br>${totals.distance.toLocaleString()} ${unit}</span><span><strong>Interval time</strong><br>${time}</span></div>${body}<footer class="deck-footer"><span>Lane Lines · ${new Date().toLocaleDateString()}</span><span>Good work. Swim with purpose.</span></footer>`}
function openDeck(){renderDeck();document.body.classList.add('show-deck');$('#deck-view').setAttribute('aria-hidden','false');window.scrollTo(0,0)}
function closeDeck(){document.body.classList.remove('show-deck');$('#deck-view').setAttribute('aria-hidden','true')}
function closeMenu(){document.body.classList.remove('show-menu');$('#menu-toggle').setAttribute('aria-expanded','false')}
function openLibrary(){closeMenu();closeLog();document.body.classList.add('show-library');$('#library-view').setAttribute('aria-hidden','false');renderLibrary();window.scrollTo(0,0)}
function closeLibrary(){document.body.classList.remove('show-library');$('#library-view').setAttribute('aria-hidden','true');window.scrollTo(0,0)}
function openLog(){closeMenu();closeLibrary();document.body.classList.add('show-log');$('#log-view').setAttribute('aria-hidden','false');renderLog();window.scrollTo(0,0)}
function closeLog(){document.body.classList.remove('show-log');$('#log-view').setAttribute('aria-hidden','true');window.scrollTo(0,0)}
$('#set-title').addEventListener('input',e=>$('#display-title').textContent=e.target.value||'Untitled set');$('#pool-length').addEventListener('change',updateTotals);$('#view-deck').onclick=openDeck;$('#close-deck').onclick=closeDeck;$('#refresh-deck').onclick=renderDeck;$('#print-deck').onclick=()=>window.print();
$('#menu-toggle').onclick=()=>{const open=!document.body.classList.contains('show-menu');document.body.classList.toggle('show-menu',open);$('#menu-toggle').setAttribute('aria-expanded',String(open))};$('#open-builder').onclick=()=>{closeMenu();closeLibrary();closeLog()};$('#open-library').onclick=openLibrary;$('#open-workout-log').onclick=openLog;$('#close-library').onclick=closeLibrary;$('#close-log').onclick=closeLog;
$('#view-stats').onclick=openStats;$('#close-stats').onclick=closeStats;$('#refresh-stats').onclick=renderStats;
const dialog=$('#save-dialog');$('#library-search').addEventListener('input',renderLibrary);$('#save-set').onclick=()=>{ $('#save-name').value=$('#set-title').value;$('#save-tags').value=$('#set-tags').value;dialog.showModal();$('#save-name').focus() };$('#confirm-save').onclick=e=>{e.preventDefault();const s=currentSet();s.title=$('#save-name').value.trim()||s.title;s.tags=$('#save-tags').value.trim();s.savedAt=Date.now();const saved=allSaved();const idx=saved.findIndex(x=>x.title===s.title);if(idx>-1)saved.splice(idx,1);saved.unshift(s);localStorage.setItem(key,JSON.stringify(saved));$('#set-title').value=s.title;$('#set-tags').value=s.tags;$('#display-title').textContent=s.title;dialog.close();renderLibrary();toast('Set saved to your library.')};
$('#library-sync-settings').onclick=openSyncSettings;$('#library-pull').onclick=pullLibrary;$('#library-push').onclick=pushLibrary;$('#save-sync-settings').onclick=e=>{e.preventDefault();saveSyncSettings({repository:$('#github-repository').value.trim(),branch:$('#github-branch').value.trim()||'main',file:$('#github-file').value.trim()||'swim-set-library.json',token:$('#github-token').value.trim()});$('#sync-dialog').close();updateSyncControls();updateLogSyncControls();toast('GitHub sync settings saved on this device.')};
$('#merge-then-push').onclick=e=>{e.preventDefault();mergeThenPush()};$('#force-push').onclick=e=>{e.preventDefault();$('#sync-conflict-dialog').close();pendingConflict=undefined;pushLibrary(true)};
$('#log-sync-settings').onclick=openLogSyncSettings;$('#log-pull').onclick=pullLog;$('#log-push').onclick=pushLog;$('#save-log-sync-settings').onclick=e=>{e.preventDefault();saveLogSyncSettings({repository:$('#log-github-repository').value.trim(),branch:$('#log-github-branch').value.trim()||'main',file:$('#log-github-file').value.trim()||'swim-workout-log.json',token:$('#log-github-token').value.trim()});$('#log-sync-dialog').close();updateLogSyncControls();toast('GitHub workout-log settings saved on this device.')};
$('#merge-log-then-push').onclick=e=>{e.preventDefault();mergeLogThenPush()};$('#force-log-push').onclick=e=>{e.preventDefault();$('#log-sync-conflict-dialog').close();pendingLogConflict=undefined;pushLog(true)};
const deleteDialog=$('#delete-confirm-dialog');deleteDialog.addEventListener('close',()=>{pendingDeletion=undefined});$('#confirm-delete').onclick=e=>{e.preventDefault();const action=pendingDeletion;deleteDialog.close();action?.()};
const logDialog=$('#log-dialog');$('#log-workout').onclick=()=>{$('#log-date').value=new Date().toISOString().slice(0,10);$('#log-notes').value='';logDialog.showModal();$('#log-notes').focus()};$('#confirm-log').onclick=e=>{e.preventDefault();const set=currentSet(),totals=setTotals(set),unit=set.pool==='25'?'yd':'m';const logs=allLogs();logs.unshift({title:set.title,date:$('#log-date').value||new Date().toISOString().slice(0,10),notes:$('#log-notes').value.trim(),total:totals.distance,unit,set});localStorage.setItem(logKey,JSON.stringify(logs));logDialog.close();renderLog();toast('Workout added to your log.')};
removeLegacySamples();seedRequestedWorkouts();loadSet({title:'Untitled set',focus:'',pool:'25',blocks:[]});renderLibrary();renderLog();updateSyncControls();updateLogSyncControls();
if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js');
